[package]
name = "terrainium"
version = "0.1.0"
edition = "2021"
default-run = "terrainium"
build = "build.rs"

[features]
terrain-schema = ["schemars"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
handlebars = "5.1.0"
home = "0.5.9"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
toml = "0.8.9"
uuid = { version = "1.7.0", features = ["v4"] }
mockall_double = "0.3.1"
prost = "0.12"
prost-types = "0.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
tracing-appender = { version = "0.2.3" }

[dependencies.schemars]
version = "0.8.16"
optional = true
features = ["preserve_order", "indexmap"]

[dev-dependencies]
mockall = { version = "0.12.1" }
serial_test = "3.0.0"

[build-dependencies]
prost-build = "0.12"
anyhow = "1.0.79"
