[package]
name = "terrainium"
version = "0.1.0"
edition = "2021"
default-run = "terrainium"
build = "build.rs"

[features]
terrain-schema = ["schemars"]

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive"] }
handlebars = "6.1.0"
home = "0.5.9"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
toml = "0.8.19"
uuid = { version = "1.10.0", features = ["v4"] }
mockall_double = "0.3.1"
prost = "0.13.2"
prost-types = "0.13.2"
time = { version = "0.3.36", features = ["local-offset", "formatting"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
tracing-appender = { version = "0.2.3" }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "process", "fs"] }
tokio-stream = { version = "0.1.16", features = ["net"] }
regex = "1.11.1"

[dependencies.schemars]
version = "0.8.21"
optional = true
features = ["preserve_order", "indexmap"]

[dev-dependencies]
mockall = { version = "0.13.0" }
serial_test = "3.1.1"
tempfile = "3.12.0"

[build-dependencies]
prost-build = "0.13.2"
anyhow = "1.0.89"
