"$schema" = "https://raw.githubusercontent.com/csd1100/terrainium/main/schema/terrain-schema.json"
name = "terrainium"
auto_apply = "all"
default_biome = "dev"

[terrain.envs]

[terrain.aliases]
t = "cargo run --"
td = "cargo run --bin terrainiumd --"
tfmt = "cargo +nightly fmt"
ttest = "cargo clippy && cargo test"

[terrain.constructors]
foreground = []
background = []

[terrain.destructors]
foreground = []
background = []

[biomes.dev.envs]
TERRAINIUM_DEV = "true"

[biomes.dev.aliases]

[biomes.dev.constructors]
background = []

[[biomes.dev.constructors.foreground]]
exe = "cargo"
args = ["run", "--", "enter", "-b", "test"]

[biomes.dev.destructors]
background = []
foreground = []

[biomes.test.envs]
TERRAINIUM_DEV = "true"

[biomes.test.aliases]
tdaemon = "cargo run --bin terrainiumd -- -f --log-level trace --run"
trenter = "exec cargo run -- enter"

[[biomes.test.constructors.foreground]]
exe = "echo"
args = ["'entering test biome'"]

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./print_num_for_10_sec"]
cwd = "./tests/scripts"

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./exit_with_1"]
cwd = "./tests/scripts/"

[[biomes.test.destructors.foreground]]
exe = "echo"
args = ["'exiting test biome'"]

[[biomes.test.destructors.background]]
exe = "/bin/zsh"
args = ["-c", "./print_num_for_10_sec"]
cwd = "./tests/scripts"
