default_biome = "example_biome"

[terrain.env]
EDITOR = "vim"

[terrain.alias]
tenter = "terrainium enter"
tedit = "terrainium edit"

[[terrain.constructors.exec]]
exe = "echo"
args = ["entering terrain"]

[[terrain.destructors.exec]]
exe = "echo"
args = ["exiting terrain"]

[biomes.example_biome.env]
EDITOR = "nvim"

[biomes.example_biome.alias]
tedit = "terrainium edit"
tenter = "terrainium enter --biome example_biome"

[[biomes.example_biome.constructors.exec]]
exe = "echo"
args = ["entering biome 'example_biome'"]

[[biomes.example_biome.destructors.exec]]
exe = "echo"
args = ["exiting biome 'example_biome'"]
