"$schema" = "https://raw.githubusercontent.com/csd1100/terrainium/main/schema/terrain-schema.json"
name = "terrainium"
auto_apply = "all"
default_biome = "test"

[terrain.envs]
TERRAINIUM_DEV = "false"

[terrain.aliases]
t = "cargo run --"
td = "cargo run --bin terrainiumd --"
ttest = "cargo clippy && cargo test"
tdaemon = "cargo run --bin terrainiumd -- -f --log-level trace --run"
tenter = "cargo run -- enter"
trenter = "exec cargo run -- enter"
tstatus = "cargo run -- status"

[terrain.constructors]
foreground = []
background = []

[terrain.destructors]
foreground = []
background = []

[biomes.dev.envs]
TERRAINIUM_DEV = "true"

[biomes.dev.aliases]

[biomes.dev.constructors]
foreground = []
background = []

[biomes.dev.destructors]
foreground = []
background = []

[biomes.test.envs]
TERRAINIUM_DEV = "true"

[biomes.test.aliases]

[[biomes.test.constructors.foreground]]
exe = "echo"
args = ["'entering test biome'"]

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./print_num_for_10_sec"]
cwd = "./tests/scripts"

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./exit_with_1"]
cwd = "./tests/scripts/"

[[biomes.test.destructors.foreground]]
exe = "echo"
args = ["'exiting test biome'"]

[[biomes.test.destructors.background]]
exe = "/bin/zsh"
args = ["-c", "./print_num_for_10_sec"]
cwd = "./tests/scripts"
