"$schema" = "https://raw.githubusercontent.com/csd1100/terrainium/main/schema/terrain-schema.json"

default_biome = "dev"

[terrain.env]
TERRAINIUM_DEV = "false"

[terrain.alias]
ttest = "cargo check && cargo test"

[biomes.dev.env]
TERRAINIUM_DEV = "true"

[biomes.test.env]
TERRAINIUM_DEV = "true"

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./test_scripts/print_num_for_10_sec"]
[[biomes.test.constructors.foreground]]
exe = "echo"
args = ["'entering test biome'"]
[[biomes.test.destructors.background]]
exe = "/bin/zsh"
args = ["-c", "./test_scripts/print_num_for_10_sec"]
[[biomes.test.destructors.foreground]]
exe = "echo"
args = ["'exiting test biome'"]
