"$schema" = "https://raw.githubusercontent.com/csd1100/terrainium/main/schema/terrain-schema.json"

default_biome = "dev"

[terrain.envs]
TERRAINIUM_DEV = "false"

[terrain.aliases]
ttest = "cargo check && cargo test"

[terrain.constructors]
foreground = []
background = []

[terrain.destructors]
foreground = []
background = []

[biomes.dev.envs]
TERRAINIUM_DEV = "true"

[biomes.dev.constructors]
foreground = []
background = []

[biomes.dev.destructors]
foreground = []
background = []

[biomes.dev.aliases]

[biomes.test.envs]
TERRAINIUM_DEV = "true"

[biomes.test.aliases]

[[biomes.test.constructors.background]]
exe = "/bin/zsh"
args = ["-c", "./tests/scripts/print_num_for_10_sec"]
[[biomes.test.constructors.foreground]]
exe = "echo"
args = ["'entering test biome'"]
[[biomes.test.destructors.background]]
exe = "/bin/zsh"
args = ["-c", "./tests/scripts/print_num_for_10_sec"]
[[biomes.test.destructors.foreground]]
exe = "echo"
args = ["'exiting test biome'"]
