[terrain.env]
VAR1 = "val1"
VAR2 = "val2"
VAR3 = "val3"

[terrain.alias]
alias1 = "run1"
alias2 = "run2"
alias3 = "run3"

[[terrain.constructors.foreground]]
exe = "run1"
args = ["something-new"]

[[terrain.destructors.foreground]]
exe = "stop1"
args = ["something-old"]
