"$schema" = "https://raw.githubusercontent.com/csd1100/terrainium/main/schema/terrain-schema.json"
default_biome = "example_biome"

[auto_apply]
enabled = false
background = false
replace = false

[terrain.envs]
EDITOR = "vim"

[terrain.aliases]
tenter = "terrainium enter"

[terrain.constructors]
background = []

[[terrain.constructors.foreground]]
exe = "/bin/echo"
args = ["entering terrain"]

[terrain.destructors]
background = []

[[terrain.destructors.foreground]]
exe = "/bin/echo"
args = ["exiting terrain"]

[biomes.example_biome.envs]
EDITOR = "nvim"

[biomes.example_biome.aliases]
tenter = "terrainium enter -b example_biome"

[biomes.example_biome.constructors]
background = []

[[biomes.example_biome.constructors.foreground]]
exe = "/bin/echo"
args = ["entering biome example_biome"]

[biomes.example_biome.destructors]
background = []

[[biomes.example_biome.destructors.foreground]]
exe = "/bin/echo"
args = ["exiting biome example_biome"]
