
[env]
VAR1 = "val1"
VAR2 = "val2"
VAR3 = "val3"

[aliases]
alias1 = "run1"
alias2 = "run2"
alias3 = "run3"

[construct]
exec = ["run1", "something-new"]

[deconstruct]
exec = ["stop1", "something-old"]
