# This file is auto-generated by terrainium
# DO NOT EDIT MANUALLY USE `terrainium edit` COMMAND TO EDIT TOML

if [ -z "$TERRAINIUM_EXECUTABLE" ]; then
    TERRAINIUM_EXECUTABLE=terrainium
fi

# USER DEFINED ALIASES: START
alias tenter="terrainium enter --biome example_biome"
alias texit="terrainium exit"
# USER DEFINED ALIASES: END
# USER DEFINED ENVS: START
export EDITOR="nvim"
export ENV_VAR="overridden_env_val"
export NESTED_POINTER="overridden_env_val-overridden_env_val-${NULL}"
export NULL_POINTER="${NULL}"
export PAGER="less"
export POINTER_ENV_VAR="overridden_env_val"
# USER DEFINED ENVS: END

function __terrainium_unset_envs() {
    unset EDITOR
    unset ENV_VAR
    unset NESTED_POINTER
    unset NULL_POINTER
    unset PAGER
    unset POINTER_ENV_VAR
}

function __terrainium_unalias() {
    unalias tenter
    unalias texit
}

function __terrainium_shell_constructor() {
    if [ "$TERRAIN_ENABLED" = "true" ]; then
        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo entering terrain
            popd &> /dev/null
        fi

        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo entering biome example_biome
            popd &> /dev/null
        fi

    fi
}

function __terrainium_shell_destructor() {
    if [ "$TERRAIN_ENABLED" = "true" ]; then
        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo exiting terrain
            popd &> /dev/null
        fi

        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo exiting biome example_biome
            popd &> /dev/null
        fi

    fi
}

function __terrainium_enter() {
    __terrainium_shell_constructor
}

function __terrain_prompt() {
    if [ "$TERRAIN_ENABLED" = "true" ]; then
        echo "terrainium(example_biome)"
    fi
}

function __terrainium_exit() {
    if [ "$TERRAIN_ENABLED" = "true" ]; then
        builtin exit
    fi
}

function __terrainium_preexec_functions() {
    tenter="(\$TERRAINIUM_EXECUTABLE enter*|$TERRAINIUM_EXECUTABLE enter*|*terrainium enter*)"
    texit="(\$TERRAINIUM_EXECUTABLE exit*|$TERRAINIUM_EXECUTABLE exit*|*terrainium exit*)"
    tconstruct="(\$TERRAINIUM_EXECUTABLE construct*|$TERRAINIUM_EXECUTABLE construct*|*terrainium construct*)"
    tdestruct="(\$TERRAINIUM_EXECUTABLE destruct*|$TERRAINIUM_EXECUTABLE destruct*|*terrainium destruct*)"

    if [ $TERRAIN_ENABLED = "true" ]; then
        case "$3" in
            $~texit)
                __terrainium_exit
                ;;
            $~tconstruct)
                __terrainium_shell_constructor
                ;;
            $~tdestruct)
                __terrainium_shell_destructor
                ;;
        esac
    fi
}

function __terrainium_zshexit_functions() {
    __terrainium_shell_destructor
    __terrainium_unalias
    __terrainium_unset_envs
    "$TERRAINIUM_EXECUTABLE" exit
}

preexec_functions=(__terrainium_preexec_functions $preexec_functions)
zshexit_functions=(__terrainium_zshexit_functions $zshexit_functions)
