# This file is auto-generated by terrainium
# DO NOT EDIT MANUALLY USE `terrain edit` COMMAND TO EDIT TOML

# USER DEFINED ALIASES: START
alias tenter="terrain enter --biome example_biome"
alias texit="terrain exit"
# USER DEFINED ALIASES: END
# USER DEFINED ENVS: START
export EDITOR="nvim"
export ENV_VAR="overridden_env_val"
export NESTED_POINTER="overridden_env_val-overridden_env_val-${NULL}"
export NULL_POINTER="${NULL}"
export PAGER="less"
export POINTER_ENV_VAR="overridden_env_val"
# USER DEFINED ENVS: END

function __terrainium_unset_envs() {
    unset EDITOR
    unset ENV_VAR
    unset NESTED_POINTER
    unset NULL_POINTER
    unset PAGER
    unset POINTER_ENV_VAR
}

function __terrainium_unalias() {
    unalias tenter
    unalias texit
}

function __terrainium_shell_constructor() {
    if [ -n "$TERRAIN_SESSION_ID" ]; then
        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo entering terrain
            popd &> /dev/null
        fi

        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo entering biome example_biome
            popd &> /dev/null
        fi

    fi
}

function __terrainium_shell_destructor() {
    if [ -n "$TERRAIN_SESSION_ID" ]; then
        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo exiting terrain
            popd &> /dev/null
        fi

        if pushd /home/user/work/terrainium &> /dev/null; then
            /bin/echo exiting biome example_biome
            popd &> /dev/null
        fi

    fi
}

function __terrainium_enter() {
    __terrainium_shell_constructor
}

function __terrain_prompt() {
    if [ -n "$TERRAIN_SESSION_ID" ]; then
        echo "${TERRAIN_NAME}(${TERRAIN_SELECTED_BIOME})"
    fi
}

function __terrainium_exit() {
    if [ -n "$TERRAIN_SESSION_ID" ]; then
        builtin exit
    fi
}

function __terrainium_preexec_functions() {
    __terrainium_parse_command "$3"
    if [ -n "$TERRAIN_SESSION_ID" ]; then
        if [ "$__terrainium_is_terrain" = "true" ]; then
            __terrainium_reexport_envs
            case "$__terrainium_verb" in
                "exit")
                    __terrainium_exit
                    ;;
                "construct")
                    __terrainium_shell_constructor
                    ;;
                "destruct")
                    __terrainium_shell_destructor
                    ;;
            esac
        fi
    fi
}

function __terrainium_precmd_functions() {
    if [ "$__TERRAIN_ENVS_EXPORTED" = "true" ]; then
        __terrainium_unexport_envs
        unset __terrainium_is_terrainium
        unset __terrainium_verb
    fi
}

function __terrainium_zshexit_functions() {
    __terrainium_reexport_envs
    __terrainium_shell_destructor
    echo "exiting terrain: ${TERRAIN_NAME} with session id: ${TERRAIN_SESSION_ID}"
    terrain exit
    __terrainium_unalias
    __terrainium_unset_envs
    __terrainium_unexport_envs
}

preexec_functions=(__terrainium_preexec_functions $preexec_functions)
precmd_functions=(__terrainium_precmd_functions $precmd_functions)
zshexit_functions=(__terrainium_zshexit_functions $zshexit_functions)
