#!/bin/sh
set -e

printf "\nChecking formatting using rustfmt\n"
cargo fmt --check
printf "\nChecking linting using clippy\n"
cargo clippy
printf "\nRunning cargo check\n"
cargo check
printf "\nRunning tests\n"
cargo test
