#!/bin/sh
set -e

printf "\nChecking formatting using rustfmt\n"
cargo +nightly fmt --check --all
printf "\nLinting using clippy\n"
cargo clippy --workspace -- -D warnings
printf "\nRunning tests\n"
cargo test --workspace
